#!/bin/bash


vbar="┃"
hbar="━"

ltcorner="┏"
rtcorner="┓"
lbcorner="┗"
rbcorner="┛"

lines=()
len=0
oldifs="$IFS"
IFS=$'\n'
while read -r line
do
        lines+=("$line")
        linelen="${#line}"
        [ "$len" -lt "$linelen" ] && len="$linelen"
done < "${1:-/dev/stdin}"

echo -n "$ltcorner"

for _ in $(seq 1 "$len")
do
echo -n "$hbar"
done

echo "$rtcorner"


for i in ${lines[*]}
do
    echo -n "$vbar"
    echo -n "$i"
    clen="${#i}"
    delta="$((len-clen))"
    [ "$delta" -gt "0" ] && tput cuf "$delta"
    echo "$vbar"
done

IFS="$oldifs"

echo -n "$lbcorner"

for _ in $(seq 1 "$len")
do
echo -n "$hbar"
done

echo "$rbcorner"
