#!/bin/python
import sys
import math

def printTopLine(length):
    print("┏" + "━"*length + "┓")

def printBotLine(length):
    print("┗" + "━"*length + "┛")

def surroundLine(length, line):
    linelen = len(line)

    #Always non-negative since 'linelen' is at most 'length'
    diff = length - linelen

    padLeft = " "*(diff // 2)
    padRight = " "*(math.ceil(diff / 2))
    print(f"┃{padLeft}{line}{padRight}┃")

def main():
    lines = []
    mwidth = 0
    for line in sys.stdin:
        lines.append(line[:-1])
        mwidth = max(mwidth, len(line[:-1]))
    printTopLine(mwidth)
    for line in lines:
        surroundLine(mwidth, line)
    printBotLine(mwidth)


if __name__ == "__main__":
    main()
