#!/bin/sh

mpdst(){
    res="$(playerctl -p "$(mpris-player)" metadata -f "{{artist}}🔨{{title}}" | sed 's/|/🪛/g;s/🔨/|/g')"
    song="$(echo "$res" | cut -d\| -f2)"
    elipsischeck="$(echo "$res" | cut -d\| -f1 | wc -c)"
    elipsis=""
    [ "$elipsischeck" -gt "25" ] && elipsis="..."
    artist="$(echo "$res" | cut -d\| -f1 | sed -E 's/(.{0,25}).*/\1/')"
    echo "$artist$elipsis - $song" | sed 's/🪛/|/g'
}

art(){
    art="$(playerctl -p "$(mpris-player)" metadata -f '{{mpris:artUrl}}')"
    curl "$art" > "$XDG_CACHE_HOME/mpris-cover"
}

art

notify-send "MPRIS [$(mpris-player)]" "$(mpdst)" -i "$XDG_CACHE_HOME/mpris-cover" >/dev/null 2>&1
