#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via rofi -dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/larbs/emoji | rofi -dmenu -fullscreen -i -columns 11 -theme-str 'element-text, element-icon, element, listview, mainbox {font: "Fira Code 46";} element{ padding: 0px 0 48px 0;} element-text{padding: 0;} listview { fixed-columns: true;}' | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
