#!/bin/bash

notify-send "Bluetooth" "Scanning for devices"
bluetoothctl --timeout=5 scan on >& /dev/null
dev="$(bluetoothctl devices | grep -vE "^\[" | cut -d' ' -f3- | dmenu  -r -p "Select which device to connect to")"
mac="$(bluetoothctl paired-devices | grep "$dev" | cut -d' ' -f2)"
[ -z "$mac" ] && {
    notify-send "Bluetooth" "Attempting to pair with device $dev"
    mac="$(bluetoothctl devices | grep "$dev" | cut -d' ' -f2)"
    bluetoothctl pair "$mac" >& /dev/null
    [ "$?" != "0" ] && {
        notify-send "Bluetooth" "Failed to pair with device $dev"
        exit 1;
    } || {
        notify-send "Bluetooth" "Connection successful."
        exit 0;
    }
}

bluetoothctl trust "$mac" >& /dev/null

bluetoothctl connect "$mac" >& /dev/null

[ "$?" != "0" ] && {
    notify-send "Bluetooth" "Failed to connect to device $dev"
} || {
    notify-send "Bluetooth" "Connection successful."
}
