#!/bin/bash

bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"

while read -r
do
    xwininfo -all -id $(xdo id -n polybar) | grep "Map State: IsViewable" &> /dev/null
    [ "$?" = "0" ] && exit 0

    stumpish mode-line
    #[ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc"

    # If pywal is installed, use it.
    wal -n -i "$(readlink -f "$bgloc")" >/dev/null 2>&1

    #pywalfox update

    #pidof dwm >/dev/null && xdotool key Hyper_L+F5

    #xwallpaper --zoom "$bgloc"
    stumpish mode-line
done < /dev/random
