#!/bin/sh

#[ -f "$HOME/.cache/songthumb.lock" ] && exit 1;

makethumbnail(){
    #touch "$HOME/.cache/songthumb.lock"

    mprisURL="$(playerctl -p "$(mpris-player)" metadata -f '{{mpris:artUrl}}')"

    if [ -n "$mprisURL" ]
    then
        curl -s "$mprisURL" > "$XDG_CACHE_HOME/songthumb"
    else
        current="$(playerctl -p "$(mpris-player)" metadata -f '{{xesam:url}}')"
        currentPath="$(echo "$current" | rg -o "file://.*" | sed 's#file://##g')"
        currentDir="$(dirname "$currentPath")"

        if ! ffmpegthumbnailer -i "$currentPath"\
                          -o "$currentDir/cover.jpg"\
                          -q 10\
                          -s 0 >/dev/null 2>&1
        then
            cp "$XDG_CONFIG_HOME/.nothumb" "$currentDir/cover.jpg"
        fi

        cp "$currentDir/cover.jpg" "$XDG_CACHE_HOME/songthumb"
    fi

    #rm "$HOME/.cache/songthumb.lock"
}

makethumbnail
