#!/bin/zsh

[ -f "$HOME/.cache/songthumb.lock" ] && exit 1;

makethumbnail(){
    touch "$HOME/.cache/songthumb.lock"

    mprisURL="$(playerctl -p "$(mpris-player)" metadata -f '{{mpris:artUrl}}')"

    if [ -n "$mprisURL" ]
    then
        curl -s "$mprisURL" > "$XDG_CACHE_HOME/songthumb.new"
    else
        current="$(mpc -f "%file%" current)"
        ffmpegthumbnailer -i "$HOME/Music/$current"\
                          -o "$XDG_CACHE_HOME/songthumb.new"\
                          -s 0 &> /dev/null
    fi

    file "$HOME/.cache/songthumb.new" | grep 'empty' &> /dev/null
    [ "$?" != "0" ] \
        && cp "$XDG_CACHE_HOME/songthumb.new" "$XDG_CACHE_HOME/songthumb" \
            || {
          cover="$HOME/Music/${current:h}/cover.jpg"
          [ -f "$cover" ] && cp "$cover" "$XDG_CACHE_HOME/songthumb" \
                  || cp "$HOME/.config/.nothumb" "$XDG_CACHE_HOME/songthumb"
        }

    rm "$HOME/.cache/songthumb.lock"
}

makethumbnail &!
