#!/bin/sh

[ -z "$1" ] && exit 2

dirpath="$1"
shift
for i in "$@"
do
dirpath="$dirpath/$i"
done

[ -d "$dirpath" ] && exit 0 || {
        echo "'$dirpath' is not a directory." 1>&2
        exit 1
    }

