#!/bin/sh


book="$(echo "$(calibredb list -f \
                       "title,series_index,series,authors"\
                       --sort-by "id"\
                       --ascending\
                       --for-machine \
                        | jq -r ' group_by(.authors) | .[] | group_by(.series) | map(sort_by(.title) | sort_by(.series_index)) | map("---;;\(.[0].series?) - \(.[0].authors);;---;;" + (map("\(.series_index): (\(.id)) \(.title) ### \(.series)")|join(";;"))) | join("\n")')" \
                       | sed -E -e 's/;;/\n/g'\
                                -e 's/---/---------------------------------------------------------/g'\
                                -e 's/null - //g'\
                                -e 's/###/                                                         /g'\
                       | rofi -dmenu \
                       | perl -pe 's/.*?[(]([0-9]+)[)].*/\1/g' \
                       | sed -E 's/^([0-9]+)$/\1/g;tx;d;:x')"

[ -z "$book" ] && exit 1

formats="$(calibredb list -w 1000\
                          -f "formats"\
                          -s "id:$book"\
                          --separator '|'\
                           | tail -n +2 \
                           | cut -d'|' -f2-\
                           | sed -E 's/\[(.*)\]/\1/g; s/\.(epub|pdf|mobi|txt), /.\1\n/g')"

prefix="$(echo "$formats" \
              | rev \
              | cut -d/ -f2- \
              | rev \
              | uniq)"

format="$(echo "$formats" \
             | rev \
             | cut -d/ -f1 \
             | rev \
             | rofi -dmenu -l 5 \
                    -p 'Open File:')"

if [ -z "$format" ]
then
    exit 1
else
    $READER "$prefix/$format"
fi
