#!/bin/zsh




res="$(xwininfo -root | grep Height | sed -E 's/[[:space:]]+//g' | cut -d: -f2)"
lines=$(((7*res - 72)/156))

book="$(calibredb list -f "title,series_index,series,authors"\
                       --sort-by "series"\
                       --ascending\
                       --separator "│"\
                       -w 500\
                        | tail -n +2\
                        | dmenu -l $lines -i\
                        | sed 's/│/|/g'\
                        | cut -d'|' -f1)"

[ -z "$book" ] && exit 1

formats="$(calibredb list -w 1000\
                          -f "formats"\
                          -s "id:$book"\
                          --separator '|'\
                           | tail -n +2 \
                           | cut -d'|' -f2-\
                           | sed -E 's/\[(.*)\]/\1/g; s/\.(epub|pdf|mobi|txt), /.\1\n/g')"

prefix="$(echo "$formats" \
              | rev \
              | cut -d/ -f2- \
              | rev \
              | uniq)"

format="$(echo "$formats" \
             | rev \
             | cut -d/ -f1 \
             | rev \
             | dmenu -l 5 \
                     -p 'Open File:')"

if [ -z "$format" ]
then
    exit 1
else
    $READER "$prefix/$format"
fi
