#!/bin/sh


res="$(mpris-control current | sed "s/️//g")"
song="$(echo "$res" | cut -d- -f2-)"
elipsischeck="$(echo "$res" | cut -d- -f1 | wc -c)"
#echo "$res"
elispis=""
[ "$elipsischeck" -gt "25" ] && elipsis="..."
artist="$(echo "$res" | cut -d- -f1 | sed -E 's/(.{0,25}).* .*/\1/')"
echo "^[^R$artist$elipsis^] -$song^] |"
