#!/bin/bash

selectPlayer(){
    local current="$(mpris-player)"
    local currentInd="$(mpris-status | grep "$current" --line-number | cut -d: -f1)"
    local ind="$((currentInd - 1))"
    echo -e "$(mpris-status)" \
        | tr ',|' '`,' \
        | sed -E "s/^($current)/➡ \1/g"\
        | csv-format \
        | tr '`' ',' \
        | sed -E 's/🪛/|/g;s/║ Playing ║/║ ▶ ║/g;s/║ Paused [ ]?║/║ ⏸ ║/g;s/║ Status [ ]?║/║ ⏯ ║/g' \
        | sed -E 's/[╚═╩╝╠╬╣╔╦╗]//g;/^$/d;s/║/​/g'\
        | rofi -dmenu \
               -a "$ind" \
               -p "Player" \
               -mesg "Choose which player will be active."\
        | sed 's/​/|/g;s/^|//g;s/|$//g' \
        | sed -E 's/[[:space:]]+/ /g;s/(^|[|]) /\1/g;s/ ($|[|])/\1/g' \
        | cut -d'|' -f1\
        | sed 's/^➡ //g'
}

selected="$(selectPlayer)"

if [ -n "$selected" ] && [ "$selected" != "Player" ]
then
    echo "$selected" | tee "$XDG_CACHE_HOME/mpris-player"
fi
