#!/bin/sh

allPlayers(){
    playerctl metadata -a -f "{{playerName}}"
}

isPlayer(){
    if [ -n "$1" ] && allPlayers | grep -E '^'"$1"'$' -q
    then
        return 0
    else
        return 1
    fi
}

[ -f "$XDG_CACHE_HOME/mpris-player" ] && {
    active=$(mpris-status | grep '|Playing|' | cut -d'|' -f1)
    player="$(cat "$XDG_CACHE_HOME/mpris-player")"
    isEmpty="$(echo "$player" | tr -d '\n' | wc -c)"

    if [ "$isEmpty" = "0" ]
    then
        if [ -z "$active" ]
        then
            allPlayers
        else
            echo "$active"
        fi
    elif [ -z "$active" ]
    then
        if isPlayer "$player"
        then
            echo "$player"
        else
            allPlayers
        fi
    else
        if echo "$active" | grep "$player" -q
        then
            echo "$player"
        else
            if [ -z "$player" ]
            then
                allPlayers
            else
                echo "$active"
            fi
        fi
    fi | head -1 | tee "$XDG_CACHE_HOME/mpris-player"
    exit 0
}

allPlayers | head -1 | tee "$XDG_CACHE_HOME/mpris-player"
