#!/bin/bash

export MPD_PORT="$(cat "$XDG_CONFIG_HOME/kaltemplate/capabilities/mpdPort.cpb")"

current=$(mpc -f "%position%💌%title%💌%artist%💌%album%" current)
queued=$(mpc -f "%position%💌%title%💌%artist%💌%album%" queued)

playlist="$(mpc -f "##💌%position%💌%title%💌%artist%💌%album%" playlist \
                | sed -E "s/#💌($current)/>💌\1/g;s/#💌($queued)/*💌\1/g;s/#💌/ 💌/g" \
                | sed 's/,/^/g;s/💌/,/g')"

curind="$(mpc -f "%position%" current | pred)"
queind="$(mpc -f "%position%" queued  | pred)"

playlistid="$(echo -e "$playlist" \
                   | csv-format \
                   | tr '^' ',' \
                   | sed -E 's/[╚═╩╝╠╬╣╔╦╗]//g;/^$/d;s/║/​/g'\
                   | rofi -dmenu -i \
                                 -r \
                                 -p "Song"\
                                 -mesg "Pick song from queue."\
                                 -a "$curind" \
                                 -u "$queind" \
                                 -selected-row "$curind"\
                   | sed 's/​/|/g'\
                   | cut -d'|' -f3)"

[[ "$playlistid" =~ [[:digit:]]+ ]] || exit 1


mpc play "$playlistid"
