#!/bin/sh

res="$(echo "$1" \
            | sed 's/^/start__/g;s/-/__minus/g;s/+/__plus/g;s/\./__dot/g;s/$/./g'\
            | ./pl-equivalent-pkgs 2>/dev/null)"

exitCode="$?"
echo "$res" | sed 's/start__//g;s/__minus/-/g;s/__plus/+/g;s/__dot/./g;'
