#!/bin/sh

while [ -n "$1" ]
do
    res="$(echo "'$1'." \
            | ./pl-equivalent-pkgs 2>/dev/null)"
    exitCode="$?"
    echo "$res" | sed -E "s/^$/Package $1 has no equivalent./" | sort -u
    shift
done
