#!/bin/sh

mpd &		     # Start Music Player Daemon
dunst &              # Use dunst for notifications
pywalfox --daemon &  # Use pywal colors in Firefox
unclutter -grab &    # Remove mouse when idle
emacs --daemon &     # Start emacs in daemon mode

mpDris2 &            # MPRIS for MPD

aw-server &
aw-watcher-window &
aw-watcher-afk &
aw-watcher-mpd &
