#!/bin/sh

pulseaudio --start & # Start PulseAudio
mpd &		     # Start Music Player Daemon
dunst &              # Use dunst for notifications
pywalfox --daemon &  # Use pywal colors in Firefox
unclutter &	     # Remove mouse when idle
emacs --daemon &     # Start emacs in daemon mode
