#!/bin/sh

dunst &              # Use dunst for notification
unclutter -grab &    # Remove mouse when idle

# mpd &		     # Start Music Player Daemon
# pywalfox start &  # Use pywal colors in Firefox
# emacs --daemon &     # Start emacs in daemon mode
# mpDris2 &            # MPRIS for MPD
# aw-server &
# aw-watcher-window &
# aw-watcher-afk &
# aw-watcher-mpd &
