#!/bin/bash


FS="$(echo -e '\001')"

#schedule url
url="https://horriblesubs.info/release-schedule/"

scheduleWeekly(){
    grep -E "^<td|\"weekday" "$LCCACHE/fetch" |
    sed -E "s#(<h2 class=\"weekday)#_^_^_\1#;tx;N;s#\n#$FS#g;P;D;:x" |
    sed -E 's$<(h2).*">$$g' |
    sed -E 's$<td.*w">$$g;s$<td.*e">$$g;s$<a.*">$$g' |
    sed -E 's$</(a|td|h2)>$$g' |
    grep -E "_\^_\^_|$(cat "$HOME/.config/livechartrc")" |
    tr '\n' '🦍' |
    sed 's/_^_^_/\n/g' |
    tail -7  > "$LCCACHE/preprocessed"

    ind=0
    IFS=$'\n'
    for weekday in $(cat "$LCCACHE/preprocessed")
    do
        d="$(echo "$weekday" | tr '🦍' $'\002' | cut -d $'\002' -f1 | cut -d' ' -f1)"
        cat /dev/null > "$LCCACHE/${d}Schedule"
        while read -r schedule
        do
            title="$(echo "$schedule" | cut -d"$FS" -f1)"
            ldate="$(echo "$schedule" | cut -d"$FS" -f2)"
            date="$(date --date="TZ=\"America/Los_Angeles\" $ldate" +"%H:%M")"
            echo "$date - $title" >> "$LCCACHE/${d}Schedule"
        done < <(echo "$weekday" | tr '🦍' $'\002' | cut -d $'\002' -f2- | tr $'\002' '\n' | head --lines="-1" )

    done
}

fetch(){
    curl -s "$url" > "$LCCACHE/fetch"
    scheduleWeekly
}

fetch
