#!/bin/bash

today="$(date +"%A")"

upcoming=false
in=-1
lines=()
while read -r line
do
    [ "$upcoming" = "true" ] && break

    format="$(echo "$line" | sed -E 's/([0-9]{2}:[0-9]{2}) - /\1☺/g')"
    IFS='☺'
    read -r time title < <(echo "$format")

    in="$(tuntil "$time")"
    [ "$in" -ge "0" ]  && {
        upcoming=true
        lines+=("$title\n")
    } || {
        lcdownload "$title"
    }

done < "$LCCACHE/${today}Schedule"

[ "$upcoming" = "false" ] && exit

mins="$(echo "$in/60" | bc)"

notify-send "Airing" "Upcoming in $mins minutes\n${lines[*]}"
