pacman('acpi').
pacman('adobe-source-han-sans-jp-fonts').
pacman('adobe-source-han-serif-jp-fonts').
pacman('adobe-source-sans-fonts').
pacman('adobe-source-serif-fonts').
pacman('alsa-utils').
pacman('android-sdk').
pacman('android-tools').
pacman('aspell').
pacman('aspell-en').
pacman('atool').
pacman('autoconf').
pacman('automake').
pacman('base').
pacman('bc').
pacman('bdf-unifont').
pacman('binutils').
pacman('bluez').
pacman('bluez-hid2hci').
pacman('bluez-libs').
pacman('bluez-plugins').
pacman('bluez-tools').
pacman('bluez-utils').
pacman('boost').
pacman('calibre').
pacman('cava').
pacman('ccls').
pacman('checkbashisms').
pacman('citra-bin').
pacman('clang').
pacman('cmake').
pacman('colorz').
pacman('cronie').
pacman('ctags').
pacman('dashbinsh').
pacman('dhcpcd').
pacman('dialog').
pacman('discord').
pacman('docker').
pacman('doxygen').
pacman('dunst').
pacman('emacs').
pacman('epub-thumbnailer-git').
pacman('etc-update').
pacman('exfat-utils').
pacman('fakeroot').
pacman('feh').
pacman('ffmpeg').
pacman('ffmpegthumbnailer').
pacman('figlet').
pacman('file').
pacman('findutils').
pacman('firefox').
pacman('fuseiso').
pacman('fzf').
pacman('gawk').
pacman('gcc').
pacman('gdb').
pacman('gettext').
pacman('gimp').
pacman('git').
pacman('gliderlabs-sigil').
pacman('global').
pacman('gprolog').
pacman('gradle').
pacman('graphviz').
pacman('grep').
pacman('groff').
pacman('gtest').
pacman('gzip').
pacman('highlight').
pacman('htop').
pacman('icecast').
pacman('intel-media-driver').
pacman('ipython').
pacman('ivy').
pacman('jdk11-openjdk').
pacman('jdk8-openjdk').
pacman('kotlin').
pacman('lf').
pacman('lib32-gnutls').
pacman('lib32-krb5').
pacman('lib32-libpulse').
pacman('lib32-libtheora').
pacman('lib32-mpg123').
pacman('lib32-openal').
pacman('libdwarf').
pacman('libmatroska').
pacman('libnotify').
pacman('libtar').
pacman('libtool').
pacman('libva-intel-driver').
pacman('libva-mesa-driver').
pacman('libva-utils').
pacman('libvterm').
pacman('libxdg-basedir').
pacman('libxft-bgra').
pacman('libxres').
pacman('libzip').
pacman('linux').
pacman('linux-clear').
pacman('linux-firmware').
pacman('llvm').
pacman('lsb-release').
pacman('lzip').
pacman('m4').
pacman('maim').
pacman('make').
pacman('man-db').
pacman('maven').
pacman('mediainfo').
pacman('mesa-vdpau').
pacman('metals').
pacman('minted').
pacman('mpc').
pacman('mpd').
pacman('mpdris2').
pacman('mpv').
pacman('mpv-mpris').
pacman('ncmpcpp').
pacman('netctl').
pacman('ninja').
pacman('nmap').
pacman('noto-fonts').
pacman('noto-fonts-emoji').
pacman('noto-fonts-extra').
pacman('npm').
pacman('ntfs-3g').
pacman('ntp').
pacman('os-prober').
pacman('otf-fira-code-symbol').
pacman('p7zip').
pacman('pacman').
pacman('pacman-contrib').
pacman('pamixer').
pacman('pandoc-bin').
pacman('patch').
pacman('perl-xls2csv').
pacman('pixz').
pacman('pkgconf').
pacman('playerctl').
pacman('poppler').
pacman('ppsspp').
pacman('pulseaudio-alsa').
pacman('pulseaudio-bluetooth').
pacman('pulsemixer').
pacman('python-mpd2').
pacman('python-mutagen').
pacman('python-pip').
pacman('python-poetry').
pacman('python-psycopg2').
pacman('python-pywal').
pacman('python-terminaltables').
pacman('python-wheel').
pacman('quicklisp').
pacman('quivira').
pacman('rapidcheck').
pacman('rclone').
pacman('refind').
pacman('reflector').
pacman('reflector-mirrorlist-update').
pacman('ripgrep').
pacman('rlwrap').
pacman('rofi').
pacman('rtv').
pacman('rustup').
pacman('sbt').
pacman('scala').
pacman('scala-docs').
pacman('scala-sources').
pacman('scrcpy').
pacman('screen').
pacman('sed').
pacman('shellcheck-bin').
pacman('simple-mtpfs-git').
pacman('sndio').
pacman('strace').
pacman('stumpwm-git').
pacman('stylelint').
pacman('stylelint-config-recommended').
pacman('sudo').
pacman('sxiv').
pacman('texinfo').
pacman('texlive-bibtexextra').
pacman('texlive-bin').
pacman('texlive-core').
pacman('texlive-fontsextra').
pacman('texlive-formatsextra').
pacman('texlive-langcyrillic').
pacman('texlive-langgreek').
pacman('texlive-langjapanese').
pacman('texlive-latexextra').
pacman('texlive-pictures').
pacman('texlive-science').
pacman('transmission-cli').
pacman('transmission-rss').
pacman('tree').
pacman('tremc').
pacman('ttf-dejavu').
pacman('ttf-fira-code').
pacman('ttf-joypixels').
pacman('ttf-roboto').
pacman('ttf-roboto-mono').
pacman('ttf-symbola').
pacman('ueberzug').
pacman('unclutter').
pacman('unrar').
pacman('unzip').
pacman('usbutils').
pacman('valgrind').
pacman('wget').
pacman('which').
pacman('wine').
pacman('wine-gecko').
pacman('wine-mono').
pacman('winetricks').
pacman('wpa_supplicant').
pacman('xboxdrv-cebtenzzre-git').
pacman('xcape').
pacman('xclip').
pacman('xdotool').
pacman('xf86-video-intel').
pacman('xf86-video-vesa').
pacman('xorg-server').
pacman('xorg-xbacklight').
pacman('xorg-xdpyinfo').
pacman('xorg-xev').
pacman('xorg-xinit').
pacman('xorg-xinput').
pacman('xorg-xprop').
pacman('xorg-xsetroot').
pacman('xorg-xwininfo').
pacman('xwallpaper').
pacman('yay').
pacman('youtube-dl').
pacman('zathura').
pacman('zathura-pdf-mupdf').
pacman('zenity').
pacman('zip').
pacman('zsh-fast-syntax-highlighting').
