pacman(start__aalib).
pacman(start__acl).
pacman(start__acpi).
pacman(start__adobe__minussource__minuscode__minuspro__minusfonts).
pacman(start__adobe__minussource__minushan__minussans__minusjp__minusfonts).
pacman(start__adobe__minussource__minushan__minusserif__minusjp__minusfonts).
pacman(start__adobe__minussource__minussans__minuspro__minusfonts).
pacman(start__adobe__minussource__minusserif__minuspro__minusfonts).
pacman(start__adwaita__minusicon__minustheme).
pacman(start__alsa__minuslib).
pacman(start__alsa__minusplugins).
pacman(start__alsa__minustools).
pacman(start__alsa__minustopology__minusconf).
pacman(start__alsa__minusucm__minusconf).
pacman(start__alsa__minusutils).
pacman(start__android__minustools).
pacman(start__android__minusudev).
pacman(start__aom).
pacman(start__archlinux__minuskeyring).
pacman(start__argon2).
pacman(start__ascii).
pacman(start__aspell).
pacman(start__aspell__minusen).
pacman(start__atk).
pacman(start__atkmm).
pacman(start__atool).
pacman(start__at__minusspi2__minusatk).
pacman(start__at__minusspi2__minuscore).
pacman(start__attr).
pacman(start__audacity).
pacman(start__audiofile).
pacman(start__audit).
pacman(start__autoconf).
pacman(start__automake).
pacman(start__avahi).
pacman(start__babl).
pacman(start__base).
pacman(start__bash).
pacman(start__bc).
pacman(start__bdf__minusunifont).
pacman(start__binutils).
pacman(start__bison).
pacman(start__blas).
pacman(start__bluetooth__minusheadset__minusbattery__minuslevel__minusgit).
pacman(start__bluez).
pacman(start__bluez__minuscups).
pacman(start__bluez__minushid2hci).
pacman(start__bluez__minuslibs).
pacman(start__bluez__minusplugins).
pacman(start__bluez__minustools).
pacman(start__bluez__minusutils).
pacman(start__boost).
pacman(start__boost__minuslibs).
pacman(start__bridge__minusutils).
pacman(start__brotli).
pacman(start__btrfs__minusprogs).
pacman(start__bubblewrap).
pacman(start__bzip2).
pacman(start__cabextract).
pacman(start__ca__minuscertificates).
pacman(start__ca__minuscertificates__minusmozilla).
pacman(start__ca__minuscertificates__minusutils).
pacman(start__cairo).
pacman(start__cairomm).
pacman(start__calibre).
pacman(start__cantarell__minusfonts).
pacman(start__cava).
pacman(start__cblas).
pacman(start__ccls).
pacman(start__cdparanoia).
pacman(start__chafa).
pacman(start__checkbashisms).
pacman(start__chmlib).
pacman(start__chromaprint).
pacman(start__chromium).
pacman(start__cifs__minusutils).
pacman(start__clang).
pacman(start__cmake).
pacman(start__colord).
pacman(start__colorz).
pacman(start__compiler__minusrt).
pacman(start__containerd).
pacman(start__coreutils).
pacman(start__cpio).
pacman(start__cppcheck).
pacman(start__cronie).
pacman(start__cryptsetup).
pacman(start__ctags).
pacman(start__cups).
pacman(start__cups__minusfilters).
pacman(start__curl).
pacman(start__dash).
pacman(start__dashbinsh).
pacman(start__dav1d).
pacman(start__db).
pacman(start__dbus).
pacman(start__dbus__minusglib).
pacman(start__dbus__minuspython).
pacman(start__dconf).
pacman(start__desktop__minusfile__minusutils).
pacman(start__device__minusmapper).
pacman(start__dhcpcd).
pacman(start__dialog).
pacman(start__diffutils).
pacman(start__discord).
pacman(start__dmraid).
pacman(start__dnssec__minusanchors).
pacman(start__docker).
pacman(start__docx2txt).
pacman(start__dosfstools).
pacman(start__double__minusconversion).
pacman(start__doxygen).
pacman(start__dpkg).
pacman(start__dunst).
pacman(start__e2fsprogs).
pacman(start__efibootmgr).
pacman(start__efivar).
pacman(start__elfutils).
pacman(start__emacs).
pacman(start__enchant).
pacman(start__epub__minusthumbnailer__minusgit).
pacman(start__epub__minustools).
pacman(start__etc__minusupdate).
pacman(start__exfat__minusutils).
pacman(start__exiv2).
pacman(start__exo).
pacman(start__expat).
pacman(start__faad2).
pacman(start__fakeroot).
pacman(start__faudio).
pacman(start__feh).
pacman(start__ffmpeg).
pacman(start__ffmpegthumbnailer).
pacman(start__fftw).
pacman(start__figlet).
pacman(start__file).
pacman(start__filesystem).
pacman(start__findutils).
pacman(start__firefox).
pacman(start__flac).
pacman(start__flex).
pacman(start__fluidsynth).
pacman(start__fmt).
pacman(start__fontconfig).
pacman(start__fortune__minusmod).
pacman(start__freetype2).
pacman(start__fribidi).
pacman(start__fuse2).
pacman(start__fuse__minuscommon).
pacman(start__fuseiso).
pacman(start__fvextra).
pacman(start__fzf).
pacman(start__gawk).
pacman(start__gc).
pacman(start__gcc).
pacman(start__gcc__minuslibs).
pacman(start__gcr).
pacman(start__gd).
pacman(start__gdb).
pacman(start__gdb__minuscommon).
pacman(start__gdbm).
pacman(start__gdk__minuspixbuf2).
pacman(start__gdl).
pacman(start__gegl).
pacman(start__geoip).
pacman(start__geoip__minusdatabase).
pacman(start__gettext).
pacman(start__ghostscript).
pacman(start__giflib).
pacman(start__gimp).
pacman(start__girara).
pacman(start__git).
pacman(start__glew).
pacman(start__glib2).
pacman(start__glibc).
pacman(start__glibmm).
pacman(start__glib__minusnetworking).
pacman(start__gliderlabs__minussigil).
pacman(start__global).
pacman(start__glslang).
pacman(start__glu).
pacman(start__gmp).
pacman(start__gnome__minusthemes__minusextra).
pacman(start__gnu__minusfree__minusfonts).
pacman(start__gnupg).
pacman(start__gnutls).
pacman(start__go).
pacman(start__gobject__minusintrospection__minusruntime).
pacman(start__gpgme).
pacman(start__gpm).
pacman(start__gprolog).
pacman(start__gptfdisk).
pacman(start__gradle).
pacman(start__graphene).
pacman(start__graphicsmagick).
pacman(start__graphite).
pacman(start__graphviz).
pacman(start__grep).
pacman(start__groff).
pacman(start__gsettings__minusdesktop__minusschemas).
pacman(start__gsfonts).
pacman(start__gsl).
pacman(start__gsm).
pacman(start__gst__minuslibav).
pacman(start__gst__minusplugins__minusbase).
pacman(start__gst__minusplugins__minusbase__minuslibs).
pacman(start__gst__minusplugins__minusgood).
pacman(start__gstreamer).
pacman(start__gtest).
pacman(start__gtk2).
pacman(start__gtk3).
pacman(start__gtk__minusengine__minusmurrine).
pacman(start__gtk__minusengines).
pacman(start__gtkmm3).
pacman(start__gtkspell3).
pacman(start__gtk__minusupdate__minusicon__minuscache).
pacman(start__gts).
pacman(start__guile).
pacman(start__gumbo__minusparser).
pacman(start__gzip).
pacman(start__harfbuzz).
pacman(start__harfbuzz__minusicu).
pacman(start__hicolor__minusicon__minustheme).
pacman(start__hidapi).
pacman(start__highlight).
pacman(start__htmlmin).
pacman(start__htop).
pacman(start__hunspell).
pacman(start__hwids).
pacman(start__hwloc).
pacman(start__hyphen).
pacman(start__iana__minusetc).
pacman(start__icecast).
pacman(start__icu).
pacman(start__id3lib).
pacman(start__ijs).
pacman(start__imagemagick).
pacman(start__imath).
pacman(start__imlib2).
pacman(start__iniparser).
pacman(start__inkscape).
pacman(start__intel__minusgmmlib).
pacman(start__intel__minusmedia__minusdriver).
pacman(start__intltool).
pacman(start__iproute2).
pacman(start__iptables).
pacman(start__iputils).
pacman(start__ipython).
pacman(start__iso__minuscodes).
pacman(start__ivy).
pacman(start__jack).
pacman(start__jansson).
pacman(start__jasper).
pacman(start__java__minusenvironment__minuscommon).
pacman(start__java__minusruntime__minuscommon).
pacman(start__jbig2dec).
pacman(start__jdk11__minusopenjdk).
pacman(start__jdk8__minusopenjdk).
pacman(start__jre11__minusopenjdk).
pacman(start__jre11__minusopenjdk__minusheadless).
pacman(start__jre8__minusopenjdk).
pacman(start__jre8__minusopenjdk__minusheadless).
pacman(start__js78).
pacman(start__json__minusc).
pacman(start__jsoncpp).
pacman(start__json__minusglib).
pacman(start__jxrlib).
pacman(start__kakoune).
pacman(start__kbd).
pacman(start__keyutils).
pacman(start__kid3__minuscommon).
pacman(start__kmod).
pacman(start__krb5).
pacman(start__kwayland).
pacman(start__lame).
pacman(start__lapack).
pacman(start__lcms2).
pacman(start__ldb).
pacman(start__ldns).
pacman(start__lensfun).
pacman(start__less).
pacman(start__lf).
pacman(start__lib32__minusacl).
pacman(start__lib32__minusalsa__minuslib).
pacman(start__lib32__minusattr).
pacman(start__lib32__minusbzip2).
pacman(start__lib32__minuscurl).
pacman(start__lib32__minusdbus).
pacman(start__lib32__minuse2fsprogs).
pacman(start__lib32__minusexpat).
pacman(start__lib32__minusfaudio).
pacman(start__lib32__minusflac).
pacman(start__lib32__minusfontconfig).
pacman(start__lib32__minusfreetype2).
pacman(start__lib32__minusgcc__minuslibs).
pacman(start__lib32__minusgettext).
pacman(start__lib32__minusglib2).
pacman(start__lib32__minusglibc).
pacman(start__lib32__minusglu).
pacman(start__lib32__minusgmp).
pacman(start__lib32__minusgnutls).
pacman(start__lib32__minusharfbuzz).
pacman(start__lib32__minusicu).
pacman(start__lib32__minuskeyutils).
pacman(start__lib32__minuskrb5).
pacman(start__lib32__minuslcms2).
pacman(start__lib32__minuslibasyncns).
pacman(start__lib32__minuslibcap).
pacman(start__lib32__minuslibdrm).
pacman(start__lib32__minuslibelf).
pacman(start__lib32__minuslibffi).
pacman(start__lib32__minuslibgcrypt).
pacman(start__lib32__minuslibglvnd).
pacman(start__lib32__minuslibgpg__minuserror).
pacman(start__lib32__minuslibice).
pacman(start__lib32__minuslibidn2).
pacman(start__lib32__minuslibjpeg__minusturbo).
pacman(start__lib32__minuslibldap).
pacman(start__lib32__minuslibltdl).
pacman(start__lib32__minuslibnl).
pacman(start__lib32__minuslibnsl).
pacman(start__lib32__minuslibogg).
pacman(start__lib32__minuslibpcap).
pacman(start__lib32__minuslibpciaccess).
pacman(start__lib32__minuslibpng).
pacman(start__lib32__minuslibpsl).
pacman(start__lib32__minuslibpulse).
pacman(start__lib32__minuslibsm).
pacman(start__lib32__minuslibsndfile).
pacman(start__lib32__minuslibssh2).
pacman(start__lib32__minuslibtasn1).
pacman(start__lib32__minuslibtheora).
pacman(start__lib32__minuslibtiff).
pacman(start__lib32__minuslibtirpc).
pacman(start__lib32__minuslibunistring).
pacman(start__lib32__minuslibunwind).
pacman(start__lib32__minuslibvorbis).
pacman(start__lib32__minuslibx11).
pacman(start__lib32__minuslibxau).
pacman(start__lib32__minuslibxcb).
pacman(start__lib32__minuslibxcrypt).
pacman(start__lib32__minuslibxcursor).
pacman(start__lib32__minuslibxdamage).
pacman(start__lib32__minuslibxdmcp).
pacman(start__lib32__minuslibxext).
pacman(start__lib32__minuslibxfixes).
pacman(start__lib32__minuslibxi).
pacman(start__lib32__minuslibxml2).
pacman(start__lib32__minuslibxrandr).
pacman(start__lib32__minuslibxrender).
pacman(start__lib32__minuslibxshmfence).
pacman(start__lib32__minuslibxtst).
pacman(start__lib32__minuslibxxf86vm).
pacman(start__lib32__minusllvm__minuslibs).
pacman(start__lib32__minuslm_sensors).
pacman(start__lib32__minusmesa).
pacman(start__lib32__minusmpg123).
pacman(start__lib32__minusncurses).
pacman(start__lib32__minusnettle).
pacman(start__lib32__minusopenal).
pacman(start__lib32__minusopenssl).
pacman(start__lib32__minusopus).
pacman(start__lib32__minusp11__minuskit).
pacman(start__lib32__minuspam).
pacman(start__lib32__minuspcre).
pacman(start__lib32__minusreadline).
pacman(start__lib32__minussdl2).
pacman(start__lib32__minussystemd).
pacman(start__lib32__minusutil__minuslinux).
pacman(start__lib32__minusvulkan__minusicd__minusloader).
pacman(start__lib32__minuswayland).
pacman(start__lib32__minusxz).
pacman(start__lib32__minuszlib).
pacman(start__lib32__minuszstd).
pacman(start__libaio).
pacman(start__libao).
pacman(start__libarchive).
pacman(start__libass).
pacman(start__libassuan).
pacman(start__libasyncns).
pacman(start__libatasmart).
pacman(start__libavc1394).
pacman(start__libavif).
pacman(start__libblockdev).
pacman(start__libbluray).
pacman(start__libbsd).
pacman(start__libbytesize).
pacman(start__libcaca).
pacman(start__libcanberra).
pacman(start__libcanberra__minuspulse).
pacman(start__libcap).
pacman(start__libcap__minusng).
pacman(start__libcddb).
pacman(start__libcdio).
pacman(start__libcdio__minusparanoia).
pacman(start__libcdr).
pacman(start__libcloudproviders).
pacman(start__libconfig).
pacman(start__libcroco).
pacman(start__libcups).
pacman(start__libcurl__minusgnutls).
pacman(start__libdaemon).
pacman(start__libdatrie).
pacman(start__libdbusmenu__minusqt5).
pacman(start__libde265).
pacman(start__libdrm).
pacman(start__libdv).
pacman(start__libdvdnav).
pacman(start__libdvdread).
pacman(start__libdwarf).
pacman(start__libebml).
pacman(start__libedit).
pacman(start__libelf).
pacman(start__libepoxy).
pacman(start__libev).
pacman(start__libevdev).
pacman(start__libevent).
pacman(start__libexif).
pacman(start__libffi).
pacman(start__libfixposix).
pacman(start__libfontenc).
pacman(start__libgcrypt).
pacman(start__libgdiplus).
pacman(start__libgexiv2).
pacman(start__libglvnd).
pacman(start__libgme).
pacman(start__libgpg__minuserror).
pacman(start__libgtop).
pacman(start__libgudev).
pacman(start__libgusb).
pacman(start__libheif).
pacman(start__libibus).
pacman(start__libical).
pacman(start__libice).
pacman(start__libid3tag).
pacman(start__libidn).
pacman(start__libidn2).
pacman(start__libiec61883).
pacman(start__libimagequant).
pacman(start__libimobiledevice).
pacman(start__libinih).
pacman(start__libinput).
pacman(start__libinstpatch).
pacman(start__libjpeg__minusturbo).
pacman(start__libkate).
pacman(start__libksba).
pacman(start__libldap).
pacman(start__liblouis).
pacman(start__liblqr).
pacman(start__libmad).
pacman(start__libmanette).
pacman(start__libmatroska).
pacman(start__libmediainfo).
pacman(start__libmfx).
pacman(start__libmicrohttpd).
pacman(start__libmikmod).
pacman(start__libmms).
pacman(start__libmng).
pacman(start__libmnl).
pacman(start__libmodplug).
pacman(start__libmp4v2).
pacman(start__libmpc).
pacman(start__libmpcdec).
pacman(start__libmpdclient).
pacman(start__libmtp).
pacman(start__libmypaint).
pacman(start__libnet).
pacman(start__libnetfilter_conntrack).
pacman(start__libnfnetlink).
pacman(start__libnfs).
pacman(start__libnftnl).
pacman(start__libnghttp2).
pacman(start__libnl).
pacman(start__libnotify).
pacman(start__libnsl).
pacman(start__libogg).
pacman(start__libomxil__minusbellagio).
pacman(start__libotf).
pacman(start__libp11__minuskit).
pacman(start__libpaper).
pacman(start__libpcap).
pacman(start__libpciaccess).
pacman(start__libpipeline).
pacman(start__libplacebo).
pacman(start__libplist).
pacman(start__libpng).
pacman(start__libproxy).
pacman(start__libpsl).
pacman(start__libpulse).
pacman(start__libraqm).
pacman(start__libraw).
pacman(start__libraw1394).
pacman(start__librevenge).
pacman(start__librsvg).
pacman(start__libsamplerate).
pacman(start__libsasl).
pacman(start__libsass).
pacman(start__libseccomp).
pacman(start__libsecret).
pacman(start__libshout).
pacman(start__libsidplayfp).
pacman(start__libsigc__plus__plus).
pacman(start__libsigsegv).
pacman(start__libsm).
pacman(start__libsndfile).
pacman(start__libsoup).
pacman(start__libsoxr).
pacman(start__libspiro).
pacman(start__libssh).
pacman(start__libssh2).
pacman(start__libstemmer).
pacman(start__libsynctex).
pacman(start__libtar).
pacman(start__libtasn1).
pacman(start__libthai).
pacman(start__libtheora).
pacman(start__libtiff).
pacman(start__libtirpc).
pacman(start__libtool).
pacman(start__libunistring).
pacman(start__libunrar).
pacman(start__libunwind).
pacman(start__libupnp).
pacman(start__liburing).
pacman(start__libusb).
pacman(start__libusbmuxd).
pacman(start__libuv).
pacman(start__libva).
pacman(start__libva__minusintel__minusdriver).
pacman(start__libva__minusmesa__minusdriver).
pacman(start__libva__minusutils).
pacman(start__libvdpau).
pacman(start__libvisio).
pacman(start__libvisual).
pacman(start__libvorbis).
pacman(start__libvpx).
pacman(start__libvterm).
pacman(start__libwacom).
pacman(start__libwebp).
pacman(start__libwmf).
pacman(start__libwpd).
pacman(start__libwpe).
pacman(start__libwpg).
pacman(start__libx11).
pacman(start__libxau).
pacman(start__libxaw).
pacman(start__libxcb).
pacman(start__libxcomposite).
pacman(start__libxcrypt).
pacman(start__libxcursor).
pacman(start__libxdamage).
pacman(start__libxdg__minusbasedir).
pacman(start__libxdmcp).
pacman(start__libxext).
pacman(start__libxfce4ui).
pacman(start__libxfce4util).
pacman(start__libxfixes).
pacman(start__libxfont2).
pacman(start__libxft__minusbgra).
pacman(start__libxi).
pacman(start__libxinerama).
pacman(start__libxkbcommon).
pacman(start__libxkbcommon__minusx11).
pacman(start__libxkbfile).
pacman(start__libxml2).
pacman(start__libxmu).
pacman(start__libxpm).
pacman(start__libxrandr).
pacman(start__libxrender).
pacman(start__libxres).
pacman(start__libxshmfence).
pacman(start__libxslt).
pacman(start__libxss).
pacman(start__libxt).
pacman(start__libxtst).
pacman(start__libxv).
pacman(start__libxvmc).
pacman(start__libxxf86vm).
pacman(start__libyaml).
pacman(start__libyuv).
pacman(start__libzen).
pacman(start__libzip).
pacman(start__licenses).
pacman(start__lilv).
pacman(start__linux).
pacman(start__linux__minusapi__minusheaders).
pacman(start__linux__minusclear).
pacman(start__linux__minusfirmware).
pacman(start__linux__minuslts).
pacman(start__linux__minuslts__minusheaders).
pacman(start__llvm).
pacman(start__llvm__minuslibs).
pacman(start__lmdb).
pacman(start__lm_sensors).
pacman(start__lsb__minusrelease).
pacman(start__lshw).
pacman(start__l__minussmash).
pacman(start__lua).
pacman(start__lua52).
pacman(start__lua53).
pacman(start__luajit).
pacman(start__lvm2).
pacman(start__lxappearance__minusgtk3).
pacman(start__lz4).
pacman(start__lzip).
pacman(start__lzo).
pacman(start__m17n__minusdb).
pacman(start__m17n__minuslib).
pacman(start__m4).
pacman(start__mailcap).
pacman(start__maim).
pacman(start__make).
pacman(start__man__minusdb).
pacman(start__mathjax).
pacman(start__maven).
pacman(start__md4c).
pacman(start__mdadm).
pacman(start__mediainfo).
pacman(start__mesa).
pacman(start__mesa__minusvdpau).
pacman(start__meson).
pacman(start__metals).
pacman(start__metis).
pacman(start__minizip).
pacman(start__minted).
pacman(start__mkinitcpio).
pacman(start__mkinitcpio__minusbusybox).
pacman(start__mkvtoolnix__minuscli).
pacman(start__mono).
pacman(start__mpc).
pacman(start__mpd).
pacman(start__mpdris2).
pacman(start__mpfr).
pacman(start__mpg123).
pacman(start__mpv).
pacman(start__mpv__minusmpris).
pacman(start__mtdev).
pacman(start__mujs).
pacman(start__mypaint__minusbrushes1).
pacman(start__ncmpcpp).
pacman(start__ncurses).
pacman(start__ndctl).
pacman(start__neofetch).
pacman(start__netctl).
pacman(start__netpbm).
pacman(start__nettle).
pacman(start__nginx__minusmainline).
pacman(start__nginx__minusmainline__minusmod__minusdav__minusext).
pacman(start__ninja).
pacman(start__nmap).
pacman(start__node__minusgyp).
pacman(start__nodejs).
pacman(start__noto__minusfonts).
pacman(start__noto__minusfonts__minusemoji).
pacman(start__noto__minusfonts__minusextra).
pacman(start__npm).
pacman(start__npth).
pacman(start__nspr).
pacman(start__nss).
pacman(start__ntfs__minus3g).
pacman(start__ntp).
pacman(start__ocl__minusicd).
pacman(start__openal).
pacman(start__opencore__minusamr).
pacman(start__openexr).
pacman(start__openjpeg2).
pacman(start__openmp).
pacman(start__openmpi).
pacman(start__openssh).
pacman(start__openssl).
pacman(start__optipng).
pacman(start__opus).
pacman(start__orc).
pacman(start__os__minusprober).
pacman(start__otf__minusfira__minuscode__minussymbol).
pacman(start__p11__minuskit).
pacman(start__p7zip).
pacman(start__pacman).
pacman(start__pacman__minusmirrorlist).
pacman(start__pam).
pacman(start__pambase).
pacman(start__pamixer).
pacman(start__pandoc__minusbin).
pacman(start__pango).
pacman(start__pangomm).
pacman(start__parallel).
pacman(start__parsec__minusbin).
pacman(start__parted).
pacman(start__patch).
pacman(start__pavucontrol).
pacman(start__pciutils).
pacman(start__pcre).
pacman(start__pcre2).
pacman(start__perl).
pacman(start__perl__minusclone).
pacman(start__perl__minusencode__minuslocale).
pacman(start__perl__minuserror).
pacman(start__perl__minusfile__minuslisting).
pacman(start__perl__minusfile__minuswhich).
pacman(start__perl__minushtml__minusparser).
pacman(start__perl__minushtml__minustagset).
pacman(start__perl__minushttp__minuscookies).
pacman(start__perl__minushttp__minusdaemon).
pacman(start__perl__minushttp__minusdate).
pacman(start__perl__minushttp__minusmessage).
pacman(start__perl__minushttp__minusnegotiate).
pacman(start__perl__minusio__minushtml).
pacman(start__perl__minusio__minussocket__minusssl).
pacman(start__perl__minuslibwww).
pacman(start__perl__minuslwp__minusmediatypes).
pacman(start__perl__minuslwp__minusprotocol__minushttps).
pacman(start__perl__minusmailtools).
pacman(start__perl__minusnet__minushttp).
pacman(start__perl__minusnet__minusssleay).
pacman(start__perl__minustimedate).
pacman(start__perl__minustry__minustiny).
pacman(start__perl__minusuri).
pacman(start__perl__minuswww__minusrobotrules).
pacman(start__perl__minusxml__minusparser).
pacman(start__pinentry).
pacman(start__pixman).
pacman(start__pixz).
pacman(start__pkgconf).
pacman(start__playerctl).
pacman(start__podofo).
pacman(start__polkit).
pacman(start__poppler).
pacman(start__poppler__minusdata).
pacman(start__poppler__minusglib).
pacman(start__popt).
pacman(start__portaudio).
pacman(start__portsmf).
pacman(start__postgresql__minuslibs).
pacman(start__potrace).
pacman(start__ppsspp).
pacman(start__premake__minusgit).
pacman(start__procps__minusng).
pacman(start__protobuf).
pacman(start__psmisc).
pacman(start__pugixml).
pacman(start__pulseaudio).
pacman(start__pulseaudio__minusalsa).
pacman(start__pulseaudio__minusbluetooth).
pacman(start__pulsemixer).
pacman(start__python).
pacman(start__python2).
pacman(start__python2__minusappdirs).
pacman(start__python2__minusbackports).
pacman(start__python2__minusbackports__dotfunctools_lru_cache).
pacman(start__python2__minusbeautifulsoup4).
pacman(start__python2__minuschardet).
pacman(start__python2__minuscssselect).
pacman(start__python2__minushtml5lib).
pacman(start__python2__minuslxml).
pacman(start__python2__minusordered__minusset).
pacman(start__python2__minuspackaging).
pacman(start__python2__minuspygments).
pacman(start__python2__minuspyparsing).
pacman(start__python2__minussetuptools).
pacman(start__python2__minussix).
pacman(start__python2__minussoupsieve).
pacman(start__python2__minuswebencodings).
pacman(start__python__minusappdirs).
pacman(start__python__minusapsw).
pacman(start__python__minusasn1crypto).
pacman(start__python__minusattrs).
pacman(start__python__minusbackcall).
pacman(start__python__minusbeautifulsoup4).
pacman(start__python__minuscachecontrol).
pacman(start__python__minuscachy).
pacman(start__python__minuscchardet).
pacman(start__python__minuscffi).
pacman(start__python__minuschardet).
pacman(start__python__minuscleo).
pacman(start__python__minusclikit).
pacman(start__python__minuscolorama).
pacman(start__python__minuscontextlib2).
pacman(start__python__minuscrashtest).
pacman(start__python__minuscryptography).
pacman(start__python__minuscss__minusparser).
pacman(start__python__minuscssselect).
pacman(start__python__minusdateutil).
pacman(start__python__minusdecorator).
pacman(start__python__minusdistlib).
pacman(start__python__minusdistro).
pacman(start__python__minusdnspython).
pacman(start__python__minusdocopt).
pacman(start__python__minusentrypoints).
pacman(start__python__minusfeedparser).
pacman(start__python__minusfilelock).
pacman(start__python__minusgobject).
pacman(start__python__minushtml2text).
pacman(start__python__minushtml5lib).
pacman(start__python__minushtml5__minusparser).
pacman(start__python__minushtmlmin).
pacman(start__python__minusidna).
pacman(start__python__minusifaddr).
pacman(start__python__minusimportlib__minusmetadata).
pacman(start__python__minusjedi).
pacman(start__python__minusjeepney).
pacman(start__python__minusjsonschema).
pacman(start__python__minuskeyring).
pacman(start__python__minuskitchen).
pacman(start__python__minuslark__minusparser).
pacman(start__python__minuslockfile).
pacman(start__python__minuslxml).
pacman(start__python__minusmarkdown).
pacman(start__python__minusmatplotlib__minusinline).
pacman(start__python__minusmechanize).
pacman(start__python__minusmpd2).
pacman(start__python__minusmsgpack).
pacman(start__python__minusmutagen).
pacman(start__python__minusnetifaces).
pacman(start__python__minusnumpy).
pacman(start__python__minusordered__minusset).
pacman(start__python__minuspackaging).
pacman(start__python__minusparso).
pacman(start__python__minuspastel).
pacman(start__python__minuspep517).
pacman(start__python__minuspexpect).
pacman(start__python__minuspickleshare).
pacman(start__python__minuspillow).
pacman(start__python__minuspip).
pacman(start__python__minuspkginfo).
pacman(start__python__minusply).
pacman(start__python__minuspoetry).
pacman(start__python__minuspoetry__minuscore).
pacman(start__python__minusprogress).
pacman(start__python__minusprompt_toolkit).
pacman(start__python__minuspsutil).
pacman(start__python__minuspsycopg2).
pacman(start__python__minusptyprocess).
pacman(start__python__minuspy7zr).
pacman(start__python__minuspybluez).
pacman(start__python__minuspychm).
pacman(start__python__minuspycparser).
pacman(start__python__minuspycryptodome).
pacman(start__python__minuspygments).
pacman(start__python__minuspylev).
pacman(start__python__minuspyopenssl).
pacman(start__python__minuspyparsing).
pacman(start__python__minuspyqt5).
pacman(start__python__minuspyqt5__minussip).
pacman(start__python__minuspyqt5__minuswebengine).
pacman(start__python__minuspyrsistent).
pacman(start__python__minuspystache).
pacman(start__python__minuspywal).
pacman(start__python__minusregex).
pacman(start__python__minusrequests).
pacman(start__python__minusrequests__minustoolbelt).
pacman(start__python__minusresolvelib).
pacman(start__python__minusretrying).
pacman(start__python__minusscipy).
pacman(start__python__minussecretstorage).
pacman(start__python__minussetuptools).
pacman(start__python__minussgmllib).
pacman(start__python__minusshellingham).
pacman(start__python__minussix).
pacman(start__python__minussoupsieve).
pacman(start__python__minusterminaltables).
pacman(start__python__minustexttable).
pacman(start__python__minustoml).
pacman(start__python__minustomlkit).
pacman(start__python__minustraitlets).
pacman(start__python__minusunrardll).
pacman(start__python__minusurllib3).
pacman(start__python__minusvirtualenv).
pacman(start__python__minuswcwidth).
pacman(start__python__minuswebencodings).
pacman(start__python__minuswheel).
pacman(start__python__minusxlib).
pacman(start__python__minusyaml).
pacman(start__python__minuszeroconf).
pacman(start__python__minuszipp).
pacman(start__qpdf).
pacman(start__qt5__minusbase).
pacman(start__qt5__minusdeclarative).
pacman(start__qt5__minusimageformats).
pacman(start__qt5__minuslocation).
pacman(start__qt5__minusmultimedia).
pacman(start__qt5__minusspeech).
pacman(start__qt5__minussvg).
pacman(start__qt5__minuswayland).
pacman(start__qt5__minuswebchannel).
pacman(start__qt5__minuswebengine).
pacman(start__quicklisp).
pacman(start__quivira).
pacman(start__rapidcheck).
pacman(start__rapidjson).
pacman(start__rav1e).
pacman(start__rclone).
pacman(start__re2).
pacman(start__readline).
pacman(start__recode).
pacman(start__refind).
pacman(start__reflector).
pacman(start__reflector__minusmirrorlist__minusupdate).
pacman(start__rest).
pacman(start__rhash).
pacman(start__ripgrep).
pacman(start__rlwrap).
pacman(start__rogue).
pacman(start__rsync).
pacman(start__rtkit).
pacman(start__rtv).
pacman(start__rubberband).
pacman(start__ruby).
pacman(start__ruby__minusffi).
pacman(start__rubygems).
pacman(start__ruby__minusirb).
pacman(start__ruby__minusopen_uri_redirections).
pacman(start__ruby__minusrb__minusinotify).
pacman(start__ruby__minusrdoc).
pacman(start__ruby__minusreline).
pacman(start__ruby__minusrexml).
pacman(start__ruby__minusrss).
pacman(start__runc).
pacman(start__run__minusparts).
pacman(start__rustup).
pacman(start__sassc).
pacman(start__sbc).
pacman(start__sbcl).
pacman(start__sbt).
pacman(start__scala).
pacman(start__scala__minusdocs).
pacman(start__scala__minussources).
pacman(start__scons).
pacman(start__scrcpy).
pacman(start__screen).
pacman(start__sdl2).
pacman(start__sed).
pacman(start__semver).
pacman(start__serd).
pacman(start__shaderc).
pacman(start__shadow).
pacman(start__shared__minusmime__minusinfo).
pacman(start__shellcheck__minusbin).
pacman(start__simple__minusmtpfs__minusgit).
pacman(start__slop).
pacman(start__smbclient).
pacman(start__snappy).
pacman(start__sndio).
pacman(start__sord).
pacman(start__sound__minustheme__minusfreedesktop).
pacman(start__soundtouch).
pacman(start__soundwire).
pacman(start__source__minushighlight).
pacman(start__speex).
pacman(start__speexdsp).
pacman(start__spicetify__minuscli).
pacman(start__spicetify__minusthemes__minusgit).
pacman(start__spirv__minustools).
pacman(start__spotify).
pacman(start__sqlite).
pacman(start__sratom).
pacman(start__srt).
pacman(start__startup__minusnotification).
pacman(start__strace).
pacman(start__stumpwm__minusgit).
pacman(start__stylelint).
pacman(start__stylelint__minusconfig__minusrecommended).
pacman(start__sudo).
pacman(start__suil).
pacman(start__suitesparse).
pacman(start__surf).
pacman(start__svt__minusav1).
pacman(start__sxiv).
pacman(start__sysfsutils).
pacman(start__systemd).
pacman(start__systemd__minuslibs).
pacman(start__systemd__minusresolvconf).
pacman(start__systemd__minussysvcompat).
pacman(start__t1lib).
pacman(start__taglib).
pacman(start__talloc).
pacman(start__tar).
pacman(start__tbb).
pacman(start__tcl).
pacman(start__tdb).
pacman(start__telegram__minusdesktop).
pacman(start__tevent).
pacman(start__texinfo).
pacman(start__texlive__minusbibtexextra).
pacman(start__texlive__minusbin).
pacman(start__texlive__minuscore).
pacman(start__texlive__minusfontsextra).
pacman(start__texlive__minusformatsextra).
pacman(start__texlive__minuslangcyrillic).
pacman(start__texlive__minuslanggreek).
pacman(start__texlive__minuslangjapanese).
pacman(start__texlive__minuslatexextra).
pacman(start__texlive__minuspictures).
pacman(start__texlive__minusscience).
pacman(start__themix__minusexport__minusspotify__minusgit).
pacman(start__themix__minusfull__minusgit).
pacman(start__themix__minusgui__minusgit).
pacman(start__themix__minusicons__minusarchdroid__minusgit).
pacman(start__themix__minusicons__minusgnome__minuscolors__minusgit).
pacman(start__themix__minusicons__minusnumix__minusgit).
pacman(start__themix__minusicons__minuspapirus__minusgit).
pacman(start__themix__minusicons__minussuru__minusplus__minusaspromauros__minusgit).
pacman(start__themix__minusicons__minussuru__minusplus__minusgit).
pacman(start__themix__minusimport__minusimages__minusgit).
pacman(start__themix__minusplugin__minusbase16__minusgit).
pacman(start__themix__minustheme__minusmateria__minusgit).
pacman(start__themix__minustheme__minusoomox__minusgit).
pacman(start__thin__minusprovisioning__minustools).
pacman(start__tinyxml2).
pacman(start__tracker3).
pacman(start__transmission__minuscli).
pacman(start__transmission__minusrss).
pacman(start__transset__minusdf).
pacman(start__tree).
pacman(start__tremc).
pacman(start__tslib).
pacman(start__ttf__minusbitstream__minusvera).
pacman(start__ttf__minusdejavu).
pacman(start__ttf__minusfira__minuscode).
pacman(start__ttf__minusjoypixels).
pacman(start__ttf__minusliberation).
pacman(start__ttf__minusopensans).
pacman(start__ttf__minusroboto).
pacman(start__ttf__minusroboto__minusmono).
pacman(start__ttf__minussymbola).
pacman(start__twolame).
pacman(start__tzdata).
pacman(start__uchardet).
pacman(start__udisks2).
pacman(start__ueberzug).
pacman(start__unclutter).
pacman(start__unrar).
pacman(start__unzip).
pacman(start__upower).
pacman(start__usbmuxd).
pacman(start__usbutils).
pacman(start__util__minuslinux).
pacman(start__util__minuslinux__minuslibs).
pacman(start__v4l__minusutils).
pacman(start__valgrind).
pacman(start__vamp__minusplugin__minussdk).
pacman(start__vid__dotstab).
pacman(start__vmaf).
pacman(start__volume_key).
pacman(start__vulkan__minusicd__minusloader).
pacman(start__w3m).
pacman(start__wavpack).
pacman(start__wayland).
pacman(start__wayland__minusprotocols).
pacman(start__webkit2gtk).
pacman(start__webrtc__minusaudio__minusprocessing).
pacman(start__wget).
pacman(start__which).
pacman(start__wildmidi).
pacman(start__wine).
pacman(start__wine__minusgecko).
pacman(start__wine__minusmono).
pacman(start__winetricks).
pacman(start__woff2).
pacman(start__wpa_supplicant).
pacman(start__wpebackend__minusfdo).
pacman(start__wxgtk3).
pacman(start__wxgtk__minuscommon).
pacman(start__x264).
pacman(start__x265).
pacman(start__xboxdrv__minuscebtenzzre__minusgit).
pacman(start__xcape).
pacman(start__xcb__minusproto).
pacman(start__xcb__minusutil).
pacman(start__xcb__minusutil__minusimage).
pacman(start__xcb__minusutil__minuskeysyms).
pacman(start__xcb__minusutil__minusrenderutil).
pacman(start__xcb__minusutil__minuswm).
pacman(start__xclip).
pacman(start__xcompmgr).
pacman(start__xdg__minusdbus__minusproxy).
pacman(start__xdg__minusutils).
pacman(start__xdo).
pacman(start__xdotool).
pacman(start__xf86__minusinput__minuslibinput).
pacman(start__xf86__minusvideo__minusintel).
pacman(start__xf86__minusvideo__minusvesa).
pacman(start__xfconf).
pacman(start__xfsprogs).
pacman(start__xkb__minusswitch).
pacman(start__xkeyboard__minusconfig).
pacman(start__xmlto).
pacman(start__xorg__minusfonts__minusencodings).
pacman(start__xorgproto).
pacman(start__xorg__minusserver).
pacman(start__xorg__minusserver__minuscommon).
pacman(start__xorg__minusserver__minusxephyr).
pacman(start__xorg__minussetxkbmap).
pacman(start__xorg__minusxauth).
pacman(start__xorg__minusxbacklight).
pacman(start__xorg__minusxdpyinfo).
pacman(start__xorg__minusxev).
pacman(start__xorg__minusxinit).
pacman(start__xorg__minusxinput).
pacman(start__xorg__minusxkbcomp).
pacman(start__xorg__minusxmessage).
pacman(start__xorg__minusxmodmap).
pacman(start__xorg__minusxprop).
pacman(start__xorg__minusxrandr).
pacman(start__xorg__minusxrdb).
pacman(start__xorg__minusxset).
pacman(start__xorg__minusxsetroot).
pacman(start__xorg__minusxwininfo).
pacman(start__xvidcore).
pacman(start__xwallpaper).
pacman(start__xxhash).
pacman(start__xz).
pacman(start__yajl).
pacman(start__yay).
pacman(start__youtube__minusdl).
pacman(start__zathura).
pacman(start__zathura__minuspdf__minusmupdf).
pacman(start__zenity).
pacman(start__zimg).
pacman(start__zip).
pacman(start__zita__minusalsa__minuspcmi).
pacman(start__zita__minusresampler).
pacman(start__zlib).
pacman(start__zsh).
pacman(start__zsh__minusfast__minussyntax__minushighlighting).
pacman(start__zstd).
pacman(start__zziplib).
