pacman('aalib').
pacman('acl').
pacman('adobe-source-code-pro-fonts').
pacman('adobe-source-han-sans-jp-fonts').
pacman('adobe-source-han-serif-jp-fonts').
pacman('adobe-source-sans-pro-fonts').
pacman('adobe-source-serif-pro-fonts').
pacman('adwaita-icon-theme').
pacman('alsa-lib').
pacman('alsa-plugins').
pacman('alsa-topology-conf').
pacman('alsa-ucm-conf').
pacman('alsa-utils').
pacman('android-tools').
pacman('android-udev').
pacman('aom').
pacman('archlinux-keyring').
pacman('argon2').
pacman('asciidoc').
pacman('aspell').
pacman('aspell-en').
pacman('atk').
pacman('atool').
pacman('at-spi2-atk').
pacman('at-spi2-core').
pacman('attr').
pacman('audiofile').
pacman('audit').
pacman('autoconf').
pacman('automake').
pacman('avahi').
pacman('babl').
pacman('base').
pacman('bash').
pacman('bdf-unifont').
pacman('binutils').
pacman('blas').
pacman('bluez').
pacman('bluez-hid2hci').
pacman('bluez-libs').
pacman('bluez-plugins').
pacman('bluez-tools').
pacman('bluez-utils').
pacman('boost').
pacman('boost-libs').
pacman('bridge-utils').
pacman('brotli').
pacman('btrfs-progs').
pacman('bubblewrap').
pacman('bzip2').
pacman('cabextract').
pacman('ca-certificates').
pacman('ca-certificates-mozilla').
pacman('ca-certificates-utils').
pacman('cairo').
pacman('calibre').
pacman('cantarell-fonts').
pacman('cava').
pacman('cblas').
pacman('ccls').
pacman('cdparanoia').
pacman('checkbashisms').
pacman('chmlib').
pacman('chromaprint').
pacman('cifs-utils').
pacman('clang').
pacman('cmake').
pacman('colord').
pacman('colorz').
pacman('compiler-rt').
pacman('containerd').
pacman('coreutils').
pacman('cpio').
pacman('cronie').
pacman('cryptsetup').
pacman('ctags').
pacman('curl').
pacman('dash').
pacman('dashbinsh').
pacman('dav1d').
pacman('db').
pacman('dbus').
pacman('dbus-glib').
pacman('dbus-python').
pacman('dconf').
pacman('desktop-file-utils').
pacman('device-mapper').
pacman('dhcpcd').
pacman('dialog').
pacman('diffutils').
pacman('discord').
pacman('dmraid').
pacman('dnssec-anchors').
pacman('docbook-xml').
pacman('docbook-xsl').
pacman('docker').
pacman('dosfstools').
pacman('double-conversion').
pacman('doxygen').
pacman('dunst').
pacman('e2fsprogs').
pacman('efibootmgr').
pacman('efivar').
pacman('elfutils').
pacman('emacs').
pacman('enchant').
pacman('epub-thumbnailer-git').
pacman('etc-update').
pacman('exfat-utils').
pacman('exiv2').
pacman('exo').
pacman('expat').
pacman('faad2').
pacman('fakechroot').
pacman('fakeroot').
pacman('faudio').
pacman('feh').
pacman('ffmpeg').
pacman('ffmpegthumbnailer').
pacman('fftw').
pacman('figlet').
pacman('file').
pacman('filesystem').
pacman('findutils').
pacman('firefox').
pacman('flac').
pacman('fluidsynth').
pacman('fontconfig').
pacman('freetype2').
pacman('fribidi').
pacman('fuse2').
pacman('fuse-common').
pacman('fuseiso').
pacman('fvextra').
pacman('fzf').
pacman('gawk').
pacman('gc').
pacman('gcc').
pacman('gcc-libs').
pacman('gcr').
pacman('gd').
pacman('gdb').
pacman('gdb-common').
pacman('gdbm').
pacman('gdk-pixbuf2').
pacman('gegl').
pacman('gettext').
pacman('ghostscript').
pacman('giflib').
pacman('gimp').
pacman('girara').
pacman('git').
pacman('glew').
pacman('glib2').
pacman('glibc').
pacman('glib-networking').
pacman('gliderlabs-sigil').
pacman('global').
pacman('glslang').
pacman('glu').
pacman('gmp').
pacman('gnome-themes-extra').
pacman('gnu-free-fonts').
pacman('gnupg').
pacman('gnutls').
pacman('gobject-introspection-runtime').
pacman('gpgme').
pacman('gpm').
pacman('gprolog').
pacman('gptfdisk').
pacman('gradle').
pacman('graphene').
pacman('graphite').
pacman('graphviz').
pacman('grep').
pacman('groff').
pacman('gsettings-desktop-schemas').
pacman('gsfonts').
pacman('gsm').
pacman('gst-libav').
pacman('gst-plugins-base').
pacman('gst-plugins-base-libs').
pacman('gst-plugins-good').
pacman('gstreamer').
pacman('gtest').
pacman('gtk2').
pacman('gtk3').
pacman('gtk-engines').
pacman('gtk-update-icon-cache').
pacman('gts').
pacman('guile').
pacman('gumbo-parser').
pacman('gzip').
pacman('harfbuzz').
pacman('harfbuzz-icu').
pacman('hicolor-icon-theme').
pacman('hidapi').
pacman('highlight').
pacman('htop').
pacman('hunspell').
pacman('hwids').
pacman('hwloc').
pacman('hyphen').
pacman('iana-etc').
pacman('icecast').
pacman('icu').
pacman('ijs').
pacman('imagemagick').
pacman('imath').
pacman('imlib2').
pacman('iniparser').
pacman('intel-gmmlib').
pacman('intel-media-driver').
pacman('iproute2').
pacman('iptables').
pacman('iputils').
pacman('ipython').
pacman('iso-codes').
pacman('ivy').
pacman('jack').
pacman('jansson').
pacman('jasper').
pacman('java-environment-common').
pacman('java-runtime-common').
pacman('jbig2dec').
pacman('jdk11-openjdk').
pacman('jdk8-openjdk').
pacman('jre11-openjdk').
pacman('jre11-openjdk-headless').
pacman('jre8-openjdk').
pacman('jre8-openjdk-headless').
pacman('js78').
pacman('json-c').
pacman('jsoncpp').
pacman('json-glib').
pacman('jxrlib').
pacman('kbd').
pacman('keyutils').
pacman('kmod').
pacman('krb5').
pacman('lame').
pacman('lapack').
pacman('lcms2').
pacman('ldb').
pacman('ldns').
pacman('lensfun').
pacman('less').
pacman('lf').
pacman('lib32-acl').
pacman('lib32-alsa-lib').
pacman('lib32-attr').
pacman('lib32-bzip2').
pacman('lib32-curl').
pacman('lib32-dbus').
pacman('lib32-e2fsprogs').
pacman('lib32-expat').
pacman('lib32-faudio').
pacman('lib32-flac').
pacman('lib32-fontconfig').
pacman('lib32-freetype2').
pacman('lib32-gcc-libs').
pacman('lib32-gettext').
pacman('lib32-glib2').
pacman('lib32-glibc').
pacman('lib32-glu').
pacman('lib32-gmp').
pacman('lib32-gnutls').
pacman('lib32-harfbuzz').
pacman('lib32-icu').
pacman('lib32-keyutils').
pacman('lib32-krb5').
pacman('lib32-lcms2').
pacman('lib32-libasyncns').
pacman('lib32-libcap').
pacman('lib32-libdrm').
pacman('lib32-libelf').
pacman('lib32-libffi').
pacman('lib32-libgcrypt').
pacman('lib32-libglvnd').
pacman('lib32-libgpg-error').
pacman('lib32-libice').
pacman('lib32-libidn2').
pacman('lib32-libjpeg-turbo').
pacman('lib32-libldap').
pacman('lib32-libltdl').
pacman('lib32-libnl').
pacman('lib32-libnsl').
pacman('lib32-libogg').
pacman('lib32-libpcap').
pacman('lib32-libpciaccess').
pacman('lib32-libpng').
pacman('lib32-libpsl').
pacman('lib32-libpulse').
pacman('lib32-libsm').
pacman('lib32-libsndfile').
pacman('lib32-libssh2').
pacman('lib32-libtasn1').
pacman('lib32-libtheora').
pacman('lib32-libtiff').
pacman('lib32-libtirpc').
pacman('lib32-libunistring').
pacman('lib32-libunwind').
pacman('lib32-libvorbis').
pacman('lib32-libx11').
pacman('lib32-libxau').
pacman('lib32-libxcb').
pacman('lib32-libxcrypt').
pacman('lib32-libxcursor').
pacman('lib32-libxdamage').
pacman('lib32-libxdmcp').
pacman('lib32-libxext').
pacman('lib32-libxfixes').
pacman('lib32-libxi').
pacman('lib32-libxml2').
pacman('lib32-libxrandr').
pacman('lib32-libxrender').
pacman('lib32-libxshmfence').
pacman('lib32-libxtst').
pacman('lib32-libxxf86vm').
pacman('lib32-llvm-libs').
pacman('lib32-lm_sensors').
pacman('lib32-mesa').
pacman('lib32-mpg123').
pacman('lib32-ncurses').
pacman('lib32-nettle').
pacman('lib32-openal').
pacman('lib32-openssl').
pacman('lib32-opus').
pacman('lib32-p11-kit').
pacman('lib32-pam').
pacman('lib32-pcre').
pacman('lib32-readline').
pacman('lib32-sdl2').
pacman('lib32-systemd').
pacman('lib32-util-linux').
pacman('lib32-vulkan-icd-loader').
pacman('lib32-wayland').
pacman('lib32-xz').
pacman('lib32-zlib').
pacman('lib32-zstd').
pacman('libaio').
pacman('libao').
pacman('libarchive').
pacman('libass').
pacman('libassuan').
pacman('libasyncns').
pacman('libatasmart').
pacman('libavc1394').
pacman('libavif').
pacman('libblockdev').
pacman('libbluray').
pacman('libbsd').
pacman('libbytesize').
pacman('libcaca').
pacman('libcanberra').
pacman('libcanberra-pulse').
pacman('libcap').
pacman('libcap-ng').
pacman('libcddb').
pacman('libcdio').
pacman('libcdio-paranoia').
pacman('libcloudproviders').
pacman('libcroco').
pacman('libcups').
pacman('libdaemon').
pacman('libdatrie').
pacman('libde265').
pacman('libdrm').
pacman('libdv').
pacman('libdvdnav').
pacman('libdvdread').
pacman('libdwarf').
pacman('libebml').
pacman('libedit').
pacman('libelf').
pacman('libepoxy').
pacman('libev').
pacman('libevdev').
pacman('libevent').
pacman('libexif').
pacman('libffi').
pacman('libfontenc').
pacman('libgcrypt').
pacman('libgdiplus').
pacman('libgexiv2').
pacman('libglvnd').
pacman('libgme').
pacman('libgpg-error').
pacman('libgtop').
pacman('libgudev').
pacman('libgusb').
pacman('libheif').
pacman('libibus').
pacman('libical').
pacman('libice').
pacman('libid3tag').
pacman('libidn').
pacman('libidn2').
pacman('libiec61883').
pacman('libimagequant').
pacman('libimobiledevice').
pacman('libinih').
pacman('libinput').
pacman('libinstpatch').
pacman('libjpeg-turbo').
pacman('libkate').
pacman('libksba').
pacman('libldap').
pacman('liblqr').
pacman('libmad').
pacman('libmanette').
pacman('libmatroska').
pacman('libmediainfo').
pacman('libmfx').
pacman('libmicrohttpd').
pacman('libmikmod').
pacman('libmms').
pacman('libmng').
pacman('libmnl').
pacman('libmodplug').
pacman('libmpc').
pacman('libmpcdec').
pacman('libmpdclient').
pacman('libmtp').
pacman('libmypaint').
pacman('libnet').
pacman('libnetfilter_conntrack').
pacman('libnfnetlink').
pacman('libnfs').
pacman('libnftnl').
pacman('libnghttp2').
pacman('libnl').
pacman('libnotify').
pacman('libnsl').
pacman('libogg').
pacman('libomxil-bellagio').
pacman('libotf').
pacman('libp11-kit').
pacman('libpaper').
pacman('libpcap').
pacman('libpciaccess').
pacman('libpipeline').
pacman('libplacebo').
pacman('libplist').
pacman('libpng').
pacman('libproxy').
pacman('libpsl').
pacman('libpulse').
pacman('libraqm').
pacman('libraw').
pacman('libraw1394').
pacman('librsvg').
pacman('libsamplerate').
pacman('libsasl').
pacman('libseccomp').
pacman('libsecret').
pacman('libshout').
pacman('libsidplayfp').
pacman('libsigsegv').
pacman('libsm').
pacman('libsndfile').
pacman('libsoup').
pacman('libsoxr').
pacman('libspiro').
pacman('libssh').
pacman('libssh2').
pacman('libsynctex').
pacman('libtar').
pacman('libtasn1').
pacman('libthai').
pacman('libtheora').
pacman('libtiff').
pacman('libtirpc').
pacman('libtool').
pacman('libunistring').
pacman('libunrar').
pacman('libunwind').
pacman('libupnp').
pacman('liburing').
pacman('libusb').
pacman('libusbmuxd').
pacman('libuv').
pacman('libva').
pacman('libva-intel-driver').
pacman('libva-mesa-driver').
pacman('libva-utils').
pacman('libvdpau').
pacman('libvisual').
pacman('libvorbis').
pacman('libvpx').
pacman('libvterm').
pacman('libwacom').
pacman('libwebp').
pacman('libwmf').
pacman('libwpe').
pacman('libx11').
pacman('libxau').
pacman('libxaw').
pacman('libxcb').
pacman('libxcomposite').
pacman('libxcrypt').
pacman('libxcursor').
pacman('libxdamage').
pacman('libxdg-basedir').
pacman('libxdmcp').
pacman('libxext').
pacman('libxfce4ui').
pacman('libxfce4util').
pacman('libxfixes').
pacman('libxfont2').
pacman('libxft-bgra').
pacman('libxi').
pacman('libxinerama').
pacman('libxkbcommon').
pacman('libxkbcommon-x11').
pacman('libxkbfile').
pacman('libxml2').
pacman('libxmu').
pacman('libxpm').
pacman('libxrandr').
pacman('libxrender').
pacman('libxres').
pacman('libxshmfence').
pacman('libxslt').
pacman('libxss').
pacman('libxt').
pacman('libxtst').
pacman('libxv').
pacman('libxvmc').
pacman('libxxf86vm').
pacman('libyaml').
pacman('libyuv').
pacman('libzen').
pacman('libzip').
pacman('licenses').
pacman('linux').
pacman('linux-api-headers').
pacman('linux-clear').
pacman('linux-firmware').
pacman('llvm').
pacman('llvm-libs').
pacman('lmdb').
pacman('lm_sensors').
pacman('lsb-release').
pacman('l-smash').
pacman('lua').
pacman('lua52').
pacman('lua53').
pacman('luajit').
pacman('lvm2').
pacman('lz4').
pacman('lzip').
pacman('lzo').
pacman('m17n-db').
pacman('m17n-lib').
pacman('m4').
pacman('mailcap').
pacman('maim').
pacman('make').
pacman('man-db').
pacman('mathjax').
pacman('maven').
pacman('md4c').
pacman('mdadm').
pacman('mediainfo').
pacman('mesa').
pacman('mesa-vdpau').
pacman('meson').
pacman('metals').
pacman('metis').
pacman('minizip').
pacman('minted').
pacman('mkinitcpio').
pacman('mkinitcpio-busybox').
pacman('mono').
pacman('mpc').
pacman('mpd').
pacman('mpdris2').
pacman('mpfr').
pacman('mpg123').
pacman('mpv').
pacman('mpv-mpris').
pacman('mtdev').
pacman('mujs').
pacman('mypaint-brushes1').
pacman('ncmpcpp').
pacman('ncurses').
pacman('ndctl').
pacman('netctl').
pacman('netpbm').
pacman('nettle').
pacman('ninja').
pacman('nmap').
pacman('node-gyp').
pacman('nodejs').
pacman('noto-fonts').
pacman('noto-fonts-emoji').
pacman('noto-fonts-extra').
pacman('npm').
pacman('npth').
pacman('nspr').
pacman('nss').
pacman('ntfs-3g').
pacman('ntp').
pacman('ocl-icd').
pacman('openal').
pacman('opencore-amr').
pacman('openexr').
pacman('openjpeg2').
pacman('openmp').
pacman('openmpi').
pacman('openssh').
pacman('openssl').
pacman('optipng').
pacman('opus').
pacman('orc').
pacman('os-prober').
pacman('otf-fira-code-symbol').
pacman('p11-kit').
pacman('p7zip').
pacman('pacman-git').
pacman('pacman-git-debug').
pacman('pacman-mirrorlist').
pacman('pam').
pacman('pambase').
pacman('pamixer').
pacman('pandoc-bin').
pacman('pango').
pacman('parted').
pacman('patch').
pacman('pciutils').
pacman('pcre').
pacman('pcre2').
pacman('perl').
pacman('perl-clone').
pacman('perl-encode-locale').
pacman('perl-error').
pacman('perl-file-listing').
pacman('perl-file-which').
pacman('perl-html-parser').
pacman('perl-html-tagset').
pacman('perl-http-cookies').
pacman('perl-http-daemon').
pacman('perl-http-date').
pacman('perl-http-message').
pacman('perl-http-negotiate').
pacman('perl-io-html').
pacman('perl-io-socket-ssl').
pacman('perl-libwww').
pacman('perl-lwp-mediatypes').
pacman('perl-lwp-protocol-https').
pacman('perl-mailtools').
pacman('perl-net-http').
pacman('perl-net-ssleay').
pacman('perl-timedate').
pacman('perl-try-tiny').
pacman('perl-uri').
pacman('perl-www-robotrules').
pacman('pinentry').
pacman('pixman').
pacman('pixz').
pacman('pkgconf').
pacman('playerctl').
pacman('podofo').
pacman('polkit').
pacman('poppler').
pacman('poppler-data').
pacman('poppler-glib').
pacman('popt').
pacman('portaudio').
pacman('postgresql-libs').
pacman('potrace').
pacman('ppsspp').
pacman('procps-ng').
pacman('protobuf').
pacman('psmisc').
pacman('pulseaudio').
pacman('pulseaudio-alsa').
pacman('pulseaudio-bluetooth').
pacman('pulsemixer').
pacman('python').
pacman('python2').
pacman('python2-appdirs').
pacman('python2-backports').
pacman('python2-backports.functools_lru_cache').
pacman('python2-beautifulsoup4').
pacman('python2-chardet').
pacman('python2-cssselect').
pacman('python2-html5lib').
pacman('python2-lxml').
pacman('python2-ordered-set').
pacman('python2-packaging').
pacman('python2-pygments').
pacman('python2-pyparsing').
pacman('python2-setuptools').
pacman('python2-six').
pacman('python2-soupsieve').
pacman('python2-webencodings').
pacman('python-appdirs').
pacman('python-apsw').
pacman('python-attrs').
pacman('python-backcall').
pacman('python-beautifulsoup4').
pacman('python-cachecontrol').
pacman('python-cachy').
pacman('python-cchardet').
pacman('python-cffi').
pacman('python-chardet').
pacman('python-cleo').
pacman('python-clikit').
pacman('python-colorama').
pacman('python-contextlib2').
pacman('python-crashtest').
pacman('python-cryptography').
pacman('python-css-parser').
pacman('python-cssselect').
pacman('python-dateutil').
pacman('python-decorator').
pacman('python-distlib').
pacman('python-distro').
pacman('python-dnspython').
pacman('python-docopt').
pacman('python-entrypoints').
pacman('python-feedparser').
pacman('python-filelock').
pacman('python-gobject').
pacman('python-html2text').
pacman('python-html5lib').
pacman('python-html5-parser').
pacman('python-idna').
pacman('python-ifaddr').
pacman('python-importlib-metadata').
pacman('python-jedi').
pacman('python-jeepney').
pacman('python-jsonschema').
pacman('python-keyring').
pacman('python-kitchen').
pacman('python-lark-parser').
pacman('python-lockfile').
pacman('python-lxml').
pacman('python-markdown').
pacman('python-matplotlib-inline').
pacman('python-mechanize').
pacman('python-mpd2').
pacman('python-msgpack').
pacman('python-mutagen').
pacman('python-netifaces').
pacman('python-numpy').
pacman('python-ordered-set').
pacman('python-packaging').
pacman('python-parso').
pacman('python-pastel').
pacman('python-pep517').
pacman('python-pexpect').
pacman('python-pickleshare').
pacman('python-pillow').
pacman('python-pip').
pacman('python-pkginfo').
pacman('python-ply').
pacman('python-poetry').
pacman('python-poetry-core').
pacman('python-progress').
pacman('python-prompt_toolkit').
pacman('python-psutil').
pacman('python-psycopg2').
pacman('python-ptyprocess').
pacman('python-py7zr').
pacman('python-pychm').
pacman('python-pycparser').
pacman('python-pycryptodome').
pacman('python-pygments').
pacman('python-pylev').
pacman('python-pyopenssl').
pacman('python-pyparsing').
pacman('python-pyqt5').
pacman('python-pyqt5-sip').
pacman('python-pyqt5-webengine').
pacman('python-pyrsistent').
pacman('python-pywal').
pacman('python-regex').
pacman('python-requests').
pacman('python-requests-toolbelt').
pacman('python-resolvelib').
pacman('python-retrying').
pacman('python-scipy').
pacman('python-secretstorage').
pacman('python-setuptools').
pacman('python-sgmllib').
pacman('python-shellingham').
pacman('python-six').
pacman('python-soupsieve').
pacman('python-terminaltables').
pacman('python-texttable').
pacman('python-toml').
pacman('python-tomlkit').
pacman('python-traitlets').
pacman('python-unrardll').
pacman('python-urllib3').
pacman('python-virtualenv').
pacman('python-wcwidth').
pacman('python-webencodings').
pacman('python-wheel').
pacman('python-xlib').
pacman('python-zeroconf').
pacman('python-zipp').
pacman('qt5-base').
pacman('qt5-declarative').
pacman('qt5-imageformats').
pacman('qt5-location').
pacman('qt5-multimedia').
pacman('qt5-speech').
pacman('qt5-svg').
pacman('qt5-wayland').
pacman('qt5-webchannel').
pacman('qt5-webengine').
pacman('quicklisp').
pacman('quivira').
pacman('rapidcheck').
pacman('rapidjson').
pacman('rav1e').
pacman('rclone').
pacman('re2').
pacman('readline').
pacman('refind').
pacman('reflector').
pacman('reflector-mirrorlist-update').
pacman('rest').
pacman('rhash').
pacman('ripgrep').
pacman('rlwrap').
pacman('rsync').
pacman('rtkit').
pacman('rtv').
pacman('rubberband').
pacman('ruby').
pacman('ruby-ffi').
pacman('rubygems').
pacman('ruby-irb').
pacman('ruby-open_uri_redirections').
pacman('ruby-rb-inotify').
pacman('ruby-reline').
pacman('ruby-rexml').
pacman('ruby-rss').
pacman('runc').
pacman('run-parts').
pacman('rustup').
pacman('sbc').
pacman('sbcl').
pacman('sbt').
pacman('scala').
pacman('scala-docs').
pacman('scala-sources').
pacman('scrcpy').
pacman('screen').
pacman('sdl2').
pacman('sed').
pacman('semver').
pacman('shaderc').
pacman('shadow').
pacman('shared-mime-info').
pacman('shellcheck-bin').
pacman('simple-mtpfs-git').
pacman('slop').
pacman('smbclient').
pacman('snappy').
pacman('sndio').
pacman('sound-theme-freedesktop').
pacman('source-highlight').
pacman('speex').
pacman('speexdsp').
pacman('spirv-tools').
pacman('sqlite').
pacman('srt').
pacman('startup-notification').
pacman('strace').
pacman('stumpwm-git').
pacman('stylelint').
pacman('stylelint-config-recommended').
pacman('sudo').
pacman('suitesparse').
pacman('svt-av1').
pacman('sxiv').
pacman('sysfsutils').
pacman('systemd').
pacman('systemd-libs').
pacman('systemd-resolvconf').
pacman('systemd-sysvcompat').
pacman('t1lib').
pacman('taglib').
pacman('talloc').
pacman('tar').
pacman('tbb').
pacman('tcl').
pacman('tdb').
pacman('tevent').
pacman('texinfo').
pacman('texlive-bibtexextra').
pacman('texlive-bin').
pacman('texlive-core').
pacman('texlive-fontsextra').
pacman('texlive-formatsextra').
pacman('texlive-langcyrillic').
pacman('texlive-langgreek').
pacman('texlive-langjapanese').
pacman('texlive-latexextra').
pacman('texlive-pictures').
pacman('texlive-science').
pacman('thin-provisioning-tools').
pacman('transmission-cli').
pacman('transmission-rss').
pacman('tree').
pacman('tremc').
pacman('tslib').
pacman('ttf-bitstream-vera').
pacman('ttf-dejavu').
pacman('ttf-fira-code').
pacman('ttf-joypixels').
pacman('ttf-liberation').
pacman('ttf-roboto').
pacman('ttf-roboto-mono').
pacman('ttf-symbola').
pacman('twolame').
pacman('tzdata').
pacman('uchardet').
pacman('udisks2').
pacman('ueberzug').
pacman('unclutter').
pacman('unrar').
pacman('unzip').
pacman('usbmuxd').
pacman('usbutils').
pacman('util-linux').
pacman('util-linux-libs').
pacman('v4l-utils').
pacman('valgrind').
pacman('vamp-plugin-sdk').
pacman('vid.stab').
pacman('vmaf').
pacman('volume_key').
pacman('vulkan-icd-loader').
pacman('wavpack').
pacman('wayland').
pacman('wayland-protocols').
pacman('webkit2gtk').
pacman('webrtc-audio-processing').
pacman('wget').
pacman('which').
pacman('wildmidi').
pacman('wine').
pacman('wine-gecko').
pacman('wine-mono').
pacman('winetricks').
pacman('woff2').
pacman('wpa_supplicant').
pacman('wpebackend-fdo').
pacman('x264').
pacman('x265').
pacman('xboxdrv-cebtenzzre-git').
pacman('xcape').
pacman('xcb-proto').
pacman('xcb-util').
pacman('xcb-util-image').
pacman('xcb-util-keysyms').
pacman('xcb-util-renderutil').
pacman('xcb-util-wm').
pacman('xclip').
pacman('xdg-dbus-proxy').
pacman('xdg-utils').
pacman('xdotool').
pacman('xf86-input-libinput').
pacman('xf86-video-intel').
pacman('xf86-video-vesa').
pacman('xfconf').
pacman('xfsprogs').
pacman('xkeyboard-config').
pacman('xorg-fonts-encodings').
pacman('xorgproto').
pacman('xorg-server').
pacman('xorg-server-common').
pacman('xorg-setxkbmap').
pacman('xorg-xauth').
pacman('xorg-xbacklight').
pacman('xorg-xdpyinfo').
pacman('xorg-xev').
pacman('xorg-xinit').
pacman('xorg-xinput').
pacman('xorg-xkbcomp').
pacman('xorg-xmessage').
pacman('xorg-xmodmap').
pacman('xorg-xprop').
pacman('xorg-xrandr').
pacman('xorg-xrdb').
pacman('xorg-xset').
pacman('xorg-xsetroot').
pacman('xorg-xwininfo').
pacman('xvidcore').
pacman('xwallpaper').
pacman('xxhash').
pacman('xz').
pacman('yajl').
pacman('yay').
pacman('youtube-dl').
pacman('zathura').
pacman('zathura-pdf-mupdf').
pacman('zenity').
pacman('zimg').
pacman('zip').
pacman('zita-alsa-pcmi').
pacman('zita-resampler').
pacman('zlib').
pacman('zsh').
pacman('zsh-fast-syntax-highlighting').
pacman('zstd').
pacman('zziplib').
