xbps('6cord').
xbps('acpi').
xbps('alsa-pipewire').
xbps('alsa-pipewire-32bit').
xbps('android-tools').
xbps('android-udev-rules').
xbps('aspell').
xbps('aspell-en').
xbps('atool').
xbps('autoconf').
xbps('automake').
xbps('base-system').
xbps('bc').
xbps('blas-devel').
xbps('bluez').
xbps('bluez-cups').
xbps('boost-devel').
xbps('calibre').
xbps('catdoc').
xbps('cava').
xbps('cblas-devel').
xbps('chromium').
xbps('clang').
xbps('clang-analyzer').
xbps('clang-tools-extra').
xbps('cmake').
xbps('cmatrix').
xbps('conky').
xbps('cppcheck').
xbps('cronie').
xbps('ctags').
xbps('curl').
xbps('dateutils').
xbps('dialog').
xbps('dmenu').
xbps('docker').
xbps('docx2txt').
xbps('doxygen').
xbps('dunst').
xbps('emacs-gtk3').
xbps('exfat-utils').
xbps('exiftool').
xbps('feh').
xbps('ffmpeg').
xbps('ffmpegthumbnailer').
xbps('figlet').
xbps('firefox').
xbps('font-adobe-source-code-pro').
xbps('fontconfig-devel').
xbps('font-firacode').
xbps('font-libertine-otf').
xbps('font-libertine-ttf').
xbps('fonts-roboto-ttf').
xbps('font-symbola').
xbps('font-unifont-bdf').
xbps('freetype-devel').
xbps('fzf').
xbps('gcc').
xbps('gcc-fortran').
xbps('gdb').
xbps('gettext').
xbps('gimp').
xbps('git').
xbps('gnupg').
xbps('gnupg2').
xbps('gource').
xbps('gprolog').
xbps('gradle').
xbps('graphviz').
xbps('groff').
xbps('grub-x86_64-efi').
xbps('gst-plugins-good1').
xbps('gst-plugins-good1-32bit').
xbps('gstreamer-vaapi').
xbps('gstreamer-vaapi-32bit').
xbps('gtest').
xbps('gtest-devel').
xbps('harfbuzz').
xbps('harfbuzz-devel').
xbps('highlight').
xbps('htop').
xbps('kitty').
xbps('lapack-devel').
xbps('lf').
xbps('libboost_iostreams1.72').
xbps('libboost_log1.72').
xbps('libboost_unit_test_framework1.72').
xbps('libcap-devel').
xbps('libconfig').
xbps('libdwarf').
xbps('libgfortran-devel').
xbps('libmatroska').
xbps('libopencv4-python3').
xbps('libpipewire').
xbps('libquadmath-devel').
xbps('libtar').
xbps('libtool').
xbps('libvdpau-32bit').
xbps('libvterm').
xbps('libxdg-basedir').
xbps('libXft-devel').
xbps('libXinerama-devel').
xbps('libzip').
xbps('linux-firmware').
xbps('llvm').
xbps('lshw').
xbps('lutris').
xbps('lxc-devel').
xbps('lzip').
xbps('maim').
xbps('make').
xbps('man-db').
xbps('mediainfo').
xbps('mpc').
xbps('mpd').
xbps('mpDris2').
xbps('mpv').
xbps('mpv-mpris').
xbps('ncdu').
xbps('ncmpcpp').
xbps('newsboat').
xbps('nmap').
xbps('nodejs').
xbps('noto-fonts-cjk').
xbps('noto-fonts-emoji').
xbps('noto-fonts-ttf').
xbps('noto-fonts-ttf-extra').
xbps('ntfs-3g').
xbps('ntp').
xbps('nvidia').
xbps('nvidia-gtklibs').
xbps('nvidia-libs').
xbps('nvidia-libs-32bit').
xbps('nvidia-opencl').
xbps('odt2txt').
xbps('oomox').
xbps('openbsd-netcat').
xbps('openjdk8').
xbps('p7zip').
xbps('pamixer').
xbps('pandoc').
xbps('patch').
xbps('pavucontrol').
xbps('picom').
xbps('pipewire').
xbps('pixz').
xbps('pkgconf').
xbps('pkg-config').
xbps('playerctl').
xbps('ppsspp').
xbps('premake5').
xbps('protobuf-devel').
xbps('psmisc').
xbps('pulseaudio').
xbps('pulseaudio-devel').
xbps('pulsemixer').
xbps('pv').
xbps('python3-devel').
xbps('python3-httplib2').
xbps('python3-ntlm-auth').
xbps('python3-numpy').
xbps('python3-pillow-simd').
xbps('python3-pip').
xbps('python3-scipy').
xbps('python3-terminaltables').
xbps('pywal').
xbps('qemu').
xbps('rclone').
xbps('refind').
xbps('ripgrep').
xbps('rlwrap').
xbps('rofi').
xbps('rtags').
xbps('rtv').
xbps('rustup').
xbps('sbcl').
xbps('scrcpy').
xbps('screen').
xbps('SDL2-32bit').
xbps('SDL2-devel').
xbps('SDL2_image-devel').
xbps('shellcheck').
xbps('simple-mtpfs').
xbps('sndio').
xbps('socat').
xbps('source-han-sans').
xbps('source-han-serif').
xbps('source-sans-pro').
xbps('source-serif').
xbps('spotify-tui').
xbps('strace').
xbps('surf').
xbps('sxiv').
xbps('texinfo').
xbps('texlive-full').
xbps('transmission').
xbps('tree').
xbps('tremc').
xbps('ueberzug').
xbps('unclutter').
xbps('unrar').
xbps('unzip').
xbps('valgrind').
xbps('virt-manager').
xbps('void-repo-multilib').
xbps('void-repo-multilib-nonfree').
xbps('void-repo-nonfree').
xbps('vulkan-loader-32bit').
xbps('Vulkan-ValidationLayers-32bit').
xbps('w3m').
xbps('wget').
xbps('wine').
xbps('wine-32bit').
xbps('wine-gecko').
xbps('wine-mono').
xbps('winetricks').
xbps('xboxdrv').
xbps('xcape').
xbps('xclip').
xbps('xdg-utils').
xbps('xdo').
xbps('xdotool').
xbps('xkb-switch').
xbps('xorg').
xbps('xorg-server-devel').
xbps('xorg-server-xephyr').
xbps('xorg-util-macros').
xbps('xterm').
xbps('xtools').
xbps('xwallpaper').
xbps('xz').
xbps('youtube-dl').
xbps('zathura').
xbps('zathura-pdf-mupdf').
xbps('zenity').
xbps('zip').
xbps('zsh').
xbps('zstd').
