#!/bin/bash

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
        watchyt="mpv --ytdl-format='bestvideo[height<=1080][fps<=30]+bestaudio'"\
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	trem="transmission-remote" \
	YT="youtube-viewer --resolution=720p -SV -C --use-color" \
        rtv="rtv --enable-media --no-flash" \
	f="$FILE" \
	e="$EDITOR" \
	v="$VISUAL" \
	z="zathura" \
        coverart="sxiv -b -s f $HOME/.cache/songthumb"

slideshow(){
    local oldIFS=$IFS
    IFS=$'\n'
    sxiv -b -s f -S 5 $(find "$HOME/Backgrounds" -type f | shuf)
    IFS=$oldIFS
}

# Common emacs utilities
alias \
    wl="emacsclient -c -e '(wl)'"


alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
        lf="lfrun" \
