#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?
do
	# Get its remaining capacity and charge status.

	capacity=$(cat "$battery"/capacity) || break
	status=$(sed "s/[Dd]ischarging/⬇/;s/[Nn]ot charging/🛑/;s/[Cc]harging/⚡/;s/[Uu]nknown/♻/;s/[Ff]ull/⚡/" "$battery"/status)

        [ "$status" =  "⬇" ] && printf "%s%%" "$capacity"  || printf "%s" "$status"

done | sed 's/ *$//'
